#!/bin/bash

export ROS_LOG_DIR=~/.ros/log/
export LOG_DATE=`date '+%y-%m-%d-%H-%M'`
env | grep ROS | tee ${ROS_LOG_DIR}/latest/${LOG_DATE}-env.log
rospack list-names | xargs -n1 sh -c 'echo -n $0; echo -n "\t\t"; rosversion $0 | tr -d "\n"; echo -n "\t"; rospack find $0' | tee ${ROS_LOG_DIR}/latest/${LOG_DATE}-rospack.log
tar -cvzh -C ${ROS_LOG_DIR} -f $LOG_DATE.tgz latest/
tar -tvzf $LOG_DATE.tgz
echo -e "\e[31mPlease send $LOG_DATE.tgz to us!\e[m"
